### ISSUE TITLE
epic 1: Homepage

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#161]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

**Homepage Logged out:**

On entering Kurate, the user is logged out.
There is a button to connect a wallet and a list of persona that are showed underneath. 
Above the persona list, there is a search field and a sorting button, which leads to a page where the user can set preferences on how the list is sorted in the homeview.

<img width="894" alt="Screenshot 2023-02-10 at 15 55 55" src="https://user-images.githubusercontent.com/9036081/218122868-ed26b515-55f6-45fb-bdd0-6fc5d5270041.png">
<img width="736" alt="Screenshot 2023-02-10 at 15 56 01" src="https://user-images.githubusercontent.com/9036081/218122895-75c0ce06-978e-4e27-aa8d-5987bb2df8b5.png">
<img width="713" alt="Screenshot 2023-02-10 at 15 56 06" src="https://user-images.githubusercontent.com/9036081/218122925-c877f103-5008-4829-b9ff-9388df4de867.png">
<img width="739" alt="Screenshot 2023-02-10 at 15 56 11" src="https://user-images.githubusercontent.com/9036081/218122946-e91b9496-93d8-47d7-857f-a7dfac00e39f.png">

**Logged in/personas**
When a wallet is connected, the wallet address that is shown in the top corner.
When a user is logged in (wallet connected), some more functionalities are available:

- switch between persona-list or chat-page.
- button to create a new persona
- viewing the persona's on favourite/draft/all

Above the list of persona's, there is a switch between persona's and chat.
There is a button to create a persona.
<img width="881" alt="Screenshot 2023-02-10 at 15 57 27" src="https://user-images.githubusercontent.com/9036081/218123131-6cbae5b2-336a-4759-aa82-58a4bba7e0ab.png">
<img width="891" alt="Screenshot 2023-02-10 at 15 57 32" src="https://user-images.githubusercontent.com/9036081/218123228-4deb0ee5-deb0-457d-9cfe-6362b3f3d16f.png">
<img width="881" alt="Screenshot 2023-02-10 at 15 57 38" src="https://user-images.githubusercontent.com/9036081/218123260-bcd5fc81-fdf3-43ef-ae4c-af54841182da.png">

**Logged in/chats**
When a user is logged in, there is the ability to chat. The chat will be sorted: new chat, active chat and closed chat.
<img width="895" alt="Screenshot 2023-02-10 at 15 58 41" src="https://user-images.githubusercontent.com/9036081/218123408-dcef70cc-76fd-46ff-a54d-b8597a7b384b.png">
<img width="908" alt="Screenshot 2023-02-10 at 15 58 47" src="https://user-images.githubusercontent.com/9036081/218123470-913a6a34-3872-4318-a2c9-4bec219a534a.png">

### Styles

- [x] Title section
- [x] Filter section (needs to become component, in progress)
- [x] Personas/Chat toggle (when logged in)
- [x] Personas sections
    - [x] Favorites
    - [x] Drafts
    - [x] All
- [x] Chats section (not built yet but should look the same as Personas sections)
    - [x] Active
    - [x] Closed
    - [x] New

- [x] _“View options” screen (no longer needed)_

### Component Styles

- [x] Persona card
- [x] Chat card
- [x] Dropdown (??)
