### ISSUE TITLE
epic 2: Persona Page

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#162]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

**Logged out**
When a user is logged out (no wallet connected), the persona page shows the header of the persona, some description and the posts of that persona. There are to action buttons: connect to post and review pending
<img width="1083" alt="Screenshot 2023-02-10 at 15 40 53" src="https://user-images.githubusercontent.com/9036081/218119506-0044f6ff-135b-41ee-9acd-2fc97f863750.png">

**Logged in** 
When the user is logged in, the user can submit a new post or go to the pending posts.
The user can also favourite a persona, or remove as favourite.
<img width="1095" alt="Screenshot 2023-02-10 at 15 40 59" src="https://user-images.githubusercontent.com/9036081/218119577-9caa16ff-d906-494b-a2e0-57479f554b06.png">
<img width="1082" alt="Screenshot 2023-02-10 at 15 41 06" src="https://user-images.githubusercontent.com/9036081/218119600-887f3c25-0dc1-44a8-8b61-1aca4c498fec.png">
<img width="1069" alt="Screenshot 2023-02-10 at 15 41 14" src="https://user-images.githubusercontent.com/9036081/218119624-7c7f6966-00fa-4f97-9974-48885e65a8b0.png">

**Pending (promote and demote)**
A user can go to the review pending on the persona page and will be able to vote on a pending post, demote or promote. The user will be informed that this action will use 1 token and the user will be informed in how many tokens are still left for this cycle.
When the user has no tokens left, this is explained.
When voted, in the overview of pending posts, this is visible by showing: "you promoted this", or "you demoted this"
The user can also vote on replies on posts, same flow as voting on posts
<img width="1078" alt="Screenshot 2023-02-10 at 15 41 20" src="https://user-images.githubusercontent.com/9036081/218119768-5c23dbcd-e440-41bb-9446-fc80f84b743a.png">
<img width="1100" alt="Screenshot 2023-02-10 at 15 41 27" src="https://user-images.githubusercontent.com/9036081/218119795-c26de233-c5c5-4094-8fb6-783e658fe793.png">
<img width="1097" alt="Screenshot 2023-02-10 at 15 41 33" src="https://user-images.githubusercontent.com/9036081/218120290-76ab42c8-b139-4837-9aaa-a5aeffecac98.png">

<img width="1094" alt="Screenshot 2023-02-10 at 15 41 39" src="https://user-images.githubusercontent.com/9036081/218119839-bd436bda-e6d1-4615-83e9-7c17d3580558.png">

<img width="1093" alt="Screenshot 2023-02-10 at 15 41 44" src="https://user-images.githubusercontent.com/9036081/218119878-98355d34-78da-46e3-8f57-b2661a5019d0.png">
<img width="1087" alt="Screenshot 2023-02-10 at 15 41 50" src="https://user-images.githubusercontent.com/9036081/218119905-502e6ae0-2481-4ad1-a750-f04f6ce90832.png">
<img width="1079" alt="Screenshot 2023-02-10 at 15 41 56" src="https://user-images.githubusercontent.com/9036081/218119937-0c267802-6556-47ed-9a4b-c3dc856bd38a.png">

### Persona

- [x] banner img
    - [x] Back button
    - [x] Add to/Remove Favorite(s) button (when logged in)
- [x] profile img
- [x] Name/pitch/description section
- [x] buttons (connect/submit, review)
- [x] Filter
- [x] Grid

### Pending posts

- [x] Title section
- [x] ”No GO left” banner
- [x] Pending title and explanation (with Learn more link)
- [x] Submit post button
- [x] Filter
- [x] Grid
    - [x] Post component including promote/demote buttons
    - [x] ”You promoted/demoted  this” button
    - [x] Include original post text on replies

### Confirm voting

- [x] Title section
- [x] Info section including Learn More link
- [x] Currently available section
- [x] Cancel/Proceed buttons
    _- [ ] "Don’t show again" checkbox (this has been removed from the design)_

### Voting error

- [x] Title section
- [x] Error message section
- [x] Currently available section
- [x] Back button
