### ISSUE TITLE
epic 3: Create Persona

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#163]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

A user can create a persona, this is done in several steps:

- putting in description
- putting in images
- creating seed posts
- submit the persona

**step 1: Text**
The user can submit a persona name, a persona pitch and a persona description, after which the user can proceed to the next step.
The persona is still saved in draft, not posted publicly yet.
<img width="957" alt="Screenshot 2023-02-10 at 15 35 52" src="https://user-images.githubusercontent.com/9036081/218118439-3536872a-803c-4297-b731-17c07894837d.png">
<img width="922" alt="Screenshot 2023-02-10 at 15 35 58" src="https://user-images.githubusercontent.com/9036081/218118461-253f231b-2df8-4715-942f-490bddf2eab3.png">
<img width="940" alt="Screenshot 2023-02-10 at 15 36 04" src="https://user-images.githubusercontent.com/9036081/218118511-faeefd29-c419-4f3b-b7bf-2417af5461f2.png">

**Step 2: Images**
The user can add a cover image and a background image.
The persona is still saved in draft, not posted publicly yet.
<img width="929" alt="Screenshot 2023-02-10 at 15 36 10" src="https://user-images.githubusercontent.com/9036081/218118597-bcfd04be-fb47-4381-867c-db145ae839c1.png">
<img width="946" alt="Screenshot 2023-02-10 at 15 36 16" src="https://user-images.githubusercontent.com/9036081/218118617-decb60ab-38a8-4606-b4d6-f356b0416b15.png">
<img width="928" alt="Screenshot 2023-02-10 at 15 36 22" src="https://user-images.githubusercontent.com/9036081/218118632-a26ed805-c09b-48ba-9237-1ff7c68c2ab4.png">

**Step 3: Seed posts**
The user will now be asked to create 5 seed posts, the persona cannot be published publicly when these 5 seed posts are not done. The persona can be saved but locally, not published yet.
<img width="1142" alt="Screenshot 2023-02-10 at 15 36 29" src="https://user-images.githubusercontent.com/9036081/218118748-ddcd1b09-b09a-4935-a2c8-51987f34b2a6.png">
<img width="924" alt="Screenshot 2023-02-10 at 15 36 35" src="https://user-images.githubusercontent.com/9036081/218118764-e7a51d68-2da9-4878-867b-babf4727bb19.png">

**Step 4: Submit**
When all is done: text, images and seed posts, the persona is ready for publishing. The user is made aware of the tokens that are needed for this action, how any tokens there are left in this cycle and a warning if the token supply of the user is insufficient. On submitting, there is a confirmation page about the persona being published.
<img width="926" alt="Screenshot 2023-02-10 at 15 36 41" src="https://user-images.githubusercontent.com/9036081/218118884-89d2970f-a51c-47dd-8114-8629a7632bb9.png">
<img width="934" alt="Screenshot 2023-02-10 at 15 36 46" src="https://user-images.githubusercontent.com/9036081/218118965-47dd2121-4d67-4769-92a2-da2273c40e04.png">

<img width="959" alt="Screenshot 2023-02-10 at 15 36 52" src="https://user-images.githubusercontent.com/9036081/218118998-fadecec7-f705-40f5-898a-4dc0d813d824.png">

### Create Persona

- [x] Title section
- [x] Name, pitch and description form w buttons

### Preview

- [x] “This is a preview” message banner
- [x] Banner (w Add button, changes to “Change” when has content)
- [x] Profile image (w Add button, changes to Reload icon and moves position when has content)
- [x] Name, pitch and description (with count icons)
- [x] Edit/Save buttons
- [x] Missing content message

### Persona saved

- [x] Title section
- [x] Confirmation message with icon and Later/Proceed buttons

### Persona Seed (this is the next step after saving persona description)

- [x] Header
    - [x] Write seed post
- [x] Write seed post and Edit persona buttons
- [x] Seed post info/count section
    - [x] Min not achieved
    - [x] Ready to publish
- [x] Grid (seed posts)
    - [x] Buttons to edit or delete seed post

### Submit

- [x] Title section
- [x] Info about GO tokens required to post
- [x] Currently available GO section
- [x] Cancel/Proceed buttons

### Error

- [x] Title section
- [x] Error message
- [x] Currently available GO
- [x] Back button

### Success

- [x] Title section
- [x] Confirmation message
- [x] Done button
