### ISSUE TITLE
epic 5: Create post

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#165]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

A user can create a post as a persona. 
First, the user will be informed that posting will cost tokens and a user has to stake reputation on a post, the user will be informed that the staked reputation will be returned in addition of extra reputation IF the post will be accepted by the community (during the voting process).

If the user has enough credit and wants to proceed, he can add text, image(s) and a link to the post.
When the creation is done, the user can submit the post and will see a confirmation screen which explains the process that will follow: the community review.

<img width="1133" alt="Screenshot 2023-02-10 at 15 25 28" src="https://user-images.githubusercontent.com/9036081/218116185-c2b68610-e8f5-4e57-b465-c9066dd79b19.png">
<img width="1093" alt="Screenshot 2023-02-10 at 15 25 36" src="https://user-images.githubusercontent.com/9036081/218116214-c8cb3159-4159-4651-8f21-129ba53a15fc.png">
<img width="1108" alt="Screenshot 2023-02-10 at 15 25 43" src="https://user-images.githubusercontent.com/9036081/218116230-d4c40a75-608e-44d8-9194-ba377a195124.png">
<img width="1103" alt="Screenshot 2023-02-10 at 15 25 49" src="https://user-images.githubusercontent.com/9036081/218116246-53903bd8-67e9-49b9-97d5-f2e4876096e4.png">
<img width="1118" alt="Screenshot 2023-02-10 at 15 25 55" src="https://user-images.githubusercontent.com/9036081/218116272-f8738ddd-2854-4925-98ee-230b979f8c51.png">
<img width="1086" alt="Screenshot 2023-02-10 at 15 26 01" src="https://user-images.githubusercontent.com/9036081/218116306-8b48b9fe-52c7-406c-b5ae-338063ab8e33.png">
<img width="1105" alt="Screenshot 2023-02-10 at 15 26 09" src="https://user-images.githubusercontent.com/9036081/218116318-4f4a6425-4cb5-4caa-b6e2-e26f56f1e143.png">
<img width="1074" alt="Screenshot 2023-02-10 at 15 26 15" src="https://user-images.githubusercontent.com/9036081/218116347-d8aa4d14-fe10-4060-9542-244a1caab3f5.png">
<img width="1119" alt="Screenshot 2023-02-10 at 15 26 20" src="https://user-images.githubusercontent.com/9036081/218116367-60783f1c-588d-4185-a211-1a3485dd967a.png">
<img width="1119" alt="Screenshot 2023-02-10 at 15 26 20" src="https://user-images.githubusercontent.com/9036081/218116387-3db3f41f-a9a9-44d1-871f-66f81783e846.png">
<img width="1128" alt="Screenshot 2023-02-10 at 15 26 26" src="https://user-images.githubusercontent.com/9036081/218116415-c813c714-dee0-4aff-90c5-4ec853e93526.png">
<img width="1112" alt="Screenshot 2023-02-10 at 15 26 32" src="https://user-images.githubusercontent.com/9036081/218116444-45f8149b-0455-45ef-8e0d-8019bcb69587.png">
<img width="1109" alt="Screenshot 2023-02-10 at 15 26 39" src="https://user-images.githubusercontent.com/9036081/218116473-954315b9-ed1f-4c3b-abcd-f134bc00be3e.png">
<img width="1087" alt="Screenshot 2023-02-10 at 15 26 46" src="https://user-images.githubusercontent.com/9036081/218117090-b76fa2de-170b-4217-a1d4-5a93fcf1e82f.png">

<img width="1099" alt="Screenshot 2023-02-10 at 15 26 53" src="https://user-images.githubusercontent.com/9036081/218116527-9927da39-0a31-4aca-895b-a3edfd78f242.png">
<img width="1076" alt="Screenshot 2023-02-10 at 15 26 59" src="https://user-images.githubusercontent.com/9036081/218116588-161a5a0e-1433-4464-ad81-a795dbab54d9.png">

### Info

- [x] Title section
- [x] GO requirement info section
- [x] Available REP tokens 
- [x] Available GO tokens
- [x] Cancel/Proceed buttons

### Error

- [x] Error info section
- [x] Available REP tokens
- [x] Available GO tokens
- [x] Back button

### Submission page

_- [ ] Title section with buttons to go back, add image (w dropdown) and submit (dropdown has been removed from design)_
- [x] Images area 
    - [x] 3 cols max, wrap for more images
    - [x] “x” icon over each image to remove it
- [x] Textarea field
_- [ ] “Add link” button (appears when post submission text is selected) (removed from design)_

### _Add link page (this functionality has been removed from the spec)_

_- [ ] Title section_
_- [ ] Display text field and label (w placeholder)_
_- [ ] Link url field and label (w placeholder)_
_- [ ] Cancel/Proceed buttons_

### Success

- [x] Title section
- [x] Confirmation text for pending post with links
- [x] Done button
