### ISSUE TITLE
epic 6: Chat

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#166]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

A user can start a chat with the poster of a post, by tapping the button in the post detail.
The user will be informed on the privacy of the chat and a code of conduct.
The user can also check the original post.
The user can now chat with the original poster, with text and images.
The user can choose to close the chat or "delete chat and block sender."
A closed chat can be re-opend, "deleted for me" or "delete and block sender".

When receiving a new chat started from a post you made, there is a warning to inform how to block when the post feels spam or inappropriate. 
 
<img width="914" alt="Screenshot 2023-02-10 at 15 21 43" src="https://user-images.githubusercontent.com/9036081/218115130-fe768959-ee12-4cf8-aedc-e236a3ca1c50.png">
<img width="900" alt="Screenshot 2023-02-10 at 15 21 50" src="https://user-images.githubusercontent.com/9036081/218115155-fd9a101c-4ebd-45d7-8fa2-2e3186aad1bb.png">
<img width="885" alt="Screenshot 2023-02-10 at 15 21 56" src="https://user-images.githubusercontent.com/9036081/218115190-39d86422-444e-4941-9370-230bd0e4eac7.png">
<img width="892" alt="Screenshot 2023-02-10 at 15 22 01" src="https://user-images.githubusercontent.com/9036081/218115216-ae67ff2c-f1e6-46d9-bc17-179476f23373.png">
<img width="894" alt="Screenshot 2023-02-10 at 15 22 07" src="https://user-images.githubusercontent.com/9036081/218115244-7d2e6c0c-1bb6-468f-ac08-f8c648d1e0db.png">
<img width="901" alt="Screenshot 2023-02-10 at 15 22 12" src="https://user-images.githubusercontent.com/9036081/218115264-c083c8e9-8c1b-44c1-b6f9-223164d55d48.png">
<img width="895" alt="Screenshot 2023-02-10 at 15 22 17" src="https://user-images.githubusercontent.com/9036081/218115296-527ed711-dbe0-4663-90fa-71ae0e4974f0.png">
<img width="913" alt="Screenshot 2023-02-10 at 15 22 22" src="https://user-images.githubusercontent.com/9036081/218115319-549fd807-92d3-4773-b1cf-72737d191935.png">
<img width="908" alt="Screenshot 2023-02-10 at 15 22 28" src="https://user-images.githubusercontent.com/9036081/218115358-30b50fc5-08c4-4a8d-8dc1-1a29fccdc22d.png">
<img width="917" alt="Screenshot 2023-02-10 at 15 22 33" src="https://user-images.githubusercontent.com/9036081/218115388-e978d509-596f-493f-9460-d3c3a0fb4b0c.png">
<img width="896" alt="Screenshot 2023-02-10 at 15 22 39" src="https://user-images.githubusercontent.com/9036081/218115421-6d271ef0-ca0e-4947-b87d-5022d413e048.png">
<img width="874" alt="Screenshot 2023-02-10 at 15 22 45" src="https://user-images.githubusercontent.com/9036081/218115477-befceac2-3d11-4191-b0e3-a341713b6c23.png">

### New chat (creating)

- [x] Title section with options icon on right side (what are the options?)
- [x] “View original post button” OR original post with icon to hide it
- [x] Privacy information section
- [x] Post section
    - [x] Textarea with placeholder
    - [x] Add image button
    - [x] Submit button

### Active chat

- [x] Title section with options icon on right side
    - [x] Close chat
    - [x] Delete & block sender (in red)
- [x] “View original post button” OR original post with icon to hide it
- [x] Chat flow
- The current viewer (me) is on the LEFT side of the chat. The other party is on the right and the image next to them is of the persona that the chat was initiated in.
- Left side text bubble has bg color
- [x] Post section
    - [x] Textarea with placeholder
    - [x] Add image button
    - [x] Submit button

### Closed chat

- [x] Title section with options icon on right side
    - [x] Re-open chat
    - [x] Delete for me
    - [x] Delete & block sender (in red)
- [x] Chat flow
- [x] Closed chat info, with links.

### New chat (receiving)

- [x] Title section with options icon on right side
    - [x] Close chat
    - [x] Delete & block sender (in red)
- [x] “View original post button” OR original post with icon to hide it
- [x] Chat message
_- [ ] Privacy and safety info section, with links (can't be implemented at the moment)_
- [x] Post section
    - [x] Textarea with placeholder
    - [x] Add image button
    - [x] Submit button

### Blocked chat

- [x] Title section with options icon on right side
    - [x] Delete for me
    - [x] Delete & block sender (in red)
- [x] “View original post button” OR original post with icon to hide it
- [x] Chat message
- [x] “Your interlocutor has deleted this chat and blocked you” message

**Comment by vojtechsimetka** [comment]
@vojtechsimetka oh we can definitely check that now :). LMK any post you made and I'll send you a chat message! 🥼

**Comment by kikipluche** [comment]
i had an incoming chat :-)
but i will send you one

**Comment by sugarpusher** [comment]
@kikipluche 
Chatted and tested with @vojtechsimetka, detecting a new incoming chat can not be implemented easily right now and we're not sure if it can be implemented with zkitter so we recommend removing it from the spec.

**Comment by kikipluche** [comment]
okay!
