### ISSUE TITLE
epic 7: Account and Activity

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#167]
[designs](https://scene.zeplin.io/project/63da627e2a13991168709051)
[design guidelines]( https://scene.zeplin.io/project/63e636dd9eb4fc19b71f1ece)
[grid]( https://scene.zeplin.io/project/63da6c0cc2cfb510d02be075)

When a user taps on the wallet address, he sees an account detail page, which shows the connected wallet, the reputation earned, the tokens left for this cycle, the cycle time, the staked reputation and the activity of the user over time.

<img width="1099" alt="Screenshot 2023-02-10 at 15 16 45" src="https://user-images.githubusercontent.com/9036081/218113898-416e7a77-9729-4b1f-a80d-ed78b34b7995.png">
<img width="1088" alt="Screenshot 2023-02-10 at 15 17 10" src="https://user-images.githubusercontent.com/9036081/218114010-571d05b7-43d7-4d80-ad8b-c9ddbb8ad04d.png">
<img width="1108" alt="Screenshot 2023-02-10 at 15 17 48" src="https://user-images.githubusercontent.com/9036081/218114095-15fe87e1-df72-4657-9c0a-c740fb4b4165.png">

### Account

- [x] Title section w abbreviated wallet address, and back and logout buttons
- [ ] Expanded wallet address section
- [x] Statistics section
    - [x] Current cycle (epoch)
    - [x] Total REP tokens
    - [x] Total GO tokens
    - [x] Staked reputation
    _- [ ] Reputation over time (not implemented)_
    - [x] Activity filter
    - [x] Activity history items

**Comment by sugarpusher** [comment]
@kikipluche 
@vojtechsimetka and I decided not to implement the reputation over time because it would be a lot of work right now.
The wallet section is currently showing the abbreviate address so that's the only thing left to do here.
