### ISSUE TITLE
Epic 1: Homepage (not logged in)

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#21]
### Homepage not logged in

On the homepage in the top left corner description of the outlet, top right corner an empty avatar, clicking on avatar leads to choose identity.
Underneath a button to connect to wallet, clicking button leads to connect wallet.
Underneath is the posts on the public timeline.

When scrolling up, the connect to wallet button stays on top, as well as an icon to suggest there are more posts when scrolling back up.

TODO:
- [x] Build the UI
- [x] Style the UI mobile
- [x] Style the UI desktop
- [x] Style the Header component mobile (mostly done, animation is a bit wonky but I’ll leave that for later)
- [x] Style the Header component desktop
- [x] Style the Button component mobile
- [x] Style the Button component desktop
- [x] Style the WalletConnect component mobile
- [x] Style the WalletConnect component desktop
- [x] Style the Post component mobile
- [x] Style the Post component desktop
- [x] Style the Posts section mobile
- [x] Style the Posts section desktop (done as far as M1, will change for following milestones)
- [x] Fetch posts from blockchain

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204793337-c0b66a48-b70a-4ca0-b45f-864af483fee5.png)

**Comment by kikipluche** [comment]
update UX:
changes: no avatars and usernames

<img width="1016" alt="Screenshot 2022-12-14 at 19 09 26" src="https://user-images.githubusercontent.com/9036081/207673441-a8929617-d6f9-4e73-9655-5e0ae9699021.png">
<img width="1019" alt="Screenshot 2022-12-14 at 19 09 59" src="https://user-images.githubusercontent.com/9036081/207673495-5e2a6798-e63c-4de4-9be4-68172c4b0ef9.png">
