### ISSUE TITLE
Epic 5: create post

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#26]
#### Create post

Top right corner a cancel button -> leads back to homepage
Top right corner a disabled publish button

Avatar username and public address  with a button to switch to other identity, clicking on it goes to choose identity.

Field to write post, when text is entered, the publish button is enabled.

on publish, switch to homepage and post is marked in green box.

- [x] Build the UI
- [x] Style the UI mobile
- [x] Style the UI desktop
- [x] Style the input-string component mobile
- [x] Style the input-string component desktop
- [x] Build the functionality

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204843197-3146707e-8f71-4bf9-b743-962b87685291.png)
![Image](https://user-images.githubusercontent.com/9036081/204843198-70c3c5b8-7547-4632-8809-e6cdc23cfff4.png)
![Image](https://user-images.githubusercontent.com/9036081/204843196-24c8841c-6db5-457a-b7c8-f1b48c41438f.png)

**Comment by kikipluche** [comment]
#### Create post

Top right corner a cancel button -> leads back to homepage
Top right corner a disabled publish button

Avatar username and public address  with a button to switch to other identity

Field to write post, when text is entered, the publish button is enabled.

on publish, switch to homepage and post is marked in green box.

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204843197-3146707e-8f71-4bf9-b743-962b87685291.png)
![Image](https://user-images.githubusercontent.com/9036081/204843198-70c3c5b8-7547-4632-8809-e6cdc23cfff4.png)
![Image](https://user-images.githubusercontent.com/9036081/204843196-24c8841c-6db5-457a-b7c8-f1b48c41438f.png)

**Comment by kikipluche** [comment]
change of UX: 
no avatars and usernames


![Image](https://user-images.githubusercontent.com/9036081/207677063-c19c7565-d2c0-4c5f-b0ee-23185f55afb3.png)



![Image](https://user-images.githubusercontent.com/9036081/207677093-58260e44-6f6b-4b9b-944c-3869ac7348cf.png)



![Image](https://user-images.githubusercontent.com/9036081/207677120-3fd4a013-8dd4-4c28-a900-a4000968c448.png)
