### ISSUE TITLE
Epic 4: Account page

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#27]
### Account page

top left corner: back button to go to homepage
top right corner: logout button: clicking this clears local storage and wallet is no longer connected.

#### Wallet and identity:
connected wallet address
selected identity is shown: 
- avatar, username and public address,
- or the anonymous identity
button next to selected identity to switch identities , clicking leads to choose identity page.

#### Identity details (only for public identity)
name : on click possible to change
profile picture
button to change profile picture

changing username:
click on name, change username in frame, on enter: green box and checkmark to confirm change.

- [x] Build the UI
- [x] Style the UI mobile
- [x] Style the UI desktop
- [x] Style the wallet-info component mobile
- [x] Style the wallet-info component desktop
- [x] Build the functionality

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204827468-d43f604f-cb06-4ba4-9788-2933b621dcf4.png)

![Image](https://user-images.githubusercontent.com/9036081/204827466-337cdd4a-3eda-4424-9db3-d469a5535c8f.png)

![Image](https://user-images.githubusercontent.com/9036081/204827467-4515b564-d977-48b5-9a7d-8f8b2a731a79.png)

![Image](https://user-images.githubusercontent.com/9036081/204827465-fa1c0423-3322-4350-b4ad-05a9ff905024.png)

**Comment by kikipluche** [comment]
change of UX:

- removal of the public account
- version logged in
- version logged out



![Image](https://user-images.githubusercontent.com/9036081/207675705-b881fbf6-c1de-4cab-bf59-5908f8ba7b26.png)



![Image](https://user-images.githubusercontent.com/9036081/207675754-1f02f640-4f50-49ca-be0f-0a5860820cb6.png)
