### ISSUE TITLE
Epic 3: Homepage logged in

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#28]
### Homepage logged in

Homepage when the user has an identity selected: users identity shows in the top right corner, clicking on it leads to account page.
Box with avatar, "share freely" and button to create post. Clicking on the whole area leads to page create post.

If the user doesn't have an identity selected, there is no create post button, but a select identity button, clicking it will lead to choose identity page.
When the user doesn't have an identity selected, the avatar in top right corner is empty, clicking on empty avatar leads to account page (no identity selected)

- [x] Build the UI
- [x] Style the UI mobile
- [x] Style the UI desktop
- [x] Style the "new-post-button" div (not a component) mobile
- [x] Style the "new-post-button" div (not a component) desktop

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204817059-f57fdfa1-1788-45c1-bcb3-2cdba9119184.png)
![Image](https://user-images.githubusercontent.com/9036081/204817060-5be6c54e-80a3-4e36-9069-9cf8c52800f0.png)
![Image](https://user-images.githubusercontent.com/9036081/204817061-21774d17-6bba-4e55-9c2c-60f487b2b8e5.png)

**Comment by kikipluche** [comment]
change of UX:

- no avatar and username
- no select identity
- create post button 


![Image](https://user-images.githubusercontent.com/9036081/207674090-4d79a19f-b86b-41f4-b28d-67d03545889f.png)



![Image](https://user-images.githubusercontent.com/9036081/207674106-6dd576dc-41be-43ca-9896-01098a652d6d.png)
